server.port: 8081
spring.application.name: authentication

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka'
    service-url:
      default-zone: 'http://localhost:8761/eureka'
  instance:
    prefer-ip-address: true
