# application settings
server.port: 8081
spring.application.name: auth

# eureka server settings
eureka:
  client:
    service-url:
      default-zone: 'http://localhost:8761/eureka'
  instance.prefer-ip-address: true

#JPA Connection details
spring.datasource:
  url: jdbc:mysql://localhost:3306/cropdeal
  username: root
  password: root

#Hibernate JPA Properties
spring.jpa:
  hibernate.ddl-auto: create
  show-sql: true
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect

#Jwt secret key
jwtSecretKey: SWFtY3JlYXRpbmdhand0aHMyNTZzZWNyZXRrZXlmb3JteXByb2plY3Rjcm9wZGVhbA==

#Email service
spring.mail:
  host: smtp.gmail.com
  port: 587
  username: cropdealproject@gmail.com
  password: hzbpvutbuylivsii
  properties:
    mail:
      smtp:
        auth: true
        starttls.enable: true

#Springdoc openapi ui
springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /api-docs

#SMS service twilio
twilio:
  auth: ad383aa0178a4703443e10533d49ef21
  sid: AC782c7944f16b2a3eecd71891dc60228a
  phone: +19853324222