# application settings
server.port: 8081
spring.application.name: auth

# eureka server settings
eureka:
  client.service-url.default-zone: 'http://localhost:8761/eureka'
  instance.prefer-ip-address: true

#JPA Connection details
spring.datasource:
  driver-class-name: oracle.jdbc.driver.OracleDriver
  url: jdbc:oracle:thin:@localhost:1521:xe
  username: cropdeal
  password: cropdeal

#Hibernate JPA Properties
spring.jpa:
  hibernate.ddl-auto: create
  show-sql: true
  properties.hibernate.dialect: org.hibernate.dialect.Oracle10gDialect

#Jwt secret key
jwtSecretKey: SWFtY3JlYXRpbmdhand0aHMyNTZzZWNyZXRrZXlmb3JteXByb2plY3Rjcm9wZGVhbA==